[package]
name = "coggo"
version = "0.1.0"
authors = ["Gregory Brutsche <gregory@brutsches.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "0.99" }
const_format = { version = "0.2.14" }
fancy-regex = { version = "0.6.0" }
lazy_static = { version = "1.4.0" }
regex = { version = "1.5.4" }
serenity = { version = "0.10", features = ["collector"] }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }