[package]
name = "coggo"
version = "0.1.0"
authors = ["Gregory Brutsche <gregory@brutsches.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.9.0" }
chrono = { version = "0.4.19" }
const_format = { version = "0.2.14" }
fancy-regex = { version = "0.6.0" }
once_cell = { version = "1.8.0" }
regex = { version = "1.5.4" }
serenity = { version = "0.10.8", features = ["collector"] }
tokio = { version = "1.7.1", features = ["macros", "rt-multi-thread"] }